version: '3'

services:
  keycloak:
    # Red Hat owned container repository; mirroring the images to Docker Hub
    image: quay.io/keycloak/keycloak:12.0.4
    # rely on .env variables
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: "${KEYCLOAK_USER}"
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASS}"
      # Uncomment the line below if you want to specify JDBC parameters. 
      # The parameter below is just an example, and it shouldn't be used 
      # in production without knowledge. It is highly recommended that 
      # you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - postgres_keycloak

  init-keycloak:
    build: init-keycloak/
    links:
      - keycloak
    # rely on .env variables

  postgres_keycloak:
    image: postgres:12.2
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  postgres_app:
    image: postgres:12.2
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${PG_APP_DB}"
      POSTGRES_USER: "${PG_APP_USER}"
      POSTGRES_PASSWORD: "${PG_APP_PASS}"
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${PG_APP_PORT}:5432"

volumes:
  postgres_keycloak_data:
      driver: local
  postgres_app_data:
      driver: local
